// Boot reliability scenarios. The server is local; no Telegram identity or user data is used.
const playwright=require(process.env.PLAYWRIGHT_PATH||'C:/Users/tanke/Desktop/NoemaDiz/node_modules/playwright');
const browserName=process.env.PLAYWRIGHT_BROWSER||'chromium',browserType=playwright[browserName];
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..','miniapp'),attempts=new Map();
const buildAssets=['index.html','tokens.js','ui.js','orb.js','app.js','screens.js','mobile.js','voice-conversation.js','style.css','mobile.css','refinement.css','design-match.css','EAGENT_DESIGN_TOKENS.json'];
const buildId='ui-'+crypto.createHash('sha256').update(Buffer.concat(buildAssets.map(name=>Buffer.concat([Buffer.from(name+'\0'),fs.readFileSync(path.join(root,name)),Buffer.from('\0')])))).digest('hex').slice(0,12);
const state={day:'2026-09-14',plan:{tasks:[],reminders:[]},tasks:[],reminders:[],notes:[],people:[],expenses:[],files:[],history:[],rules:[],settings:{mode:'text',timezone:'Europe/Moscow',home_widgets:[],experimental_realtime:false,experimental_realtime_available:false,experimental_wake_enabled:false,telemetry_enabled:false,voice_preferences:{gender:'male',voice:'ru-RU-DmitryNeural',speed:1,pitch:1,volume:1},briefing:{enabled:false,time:'08:30',topics:'',city:''}}};
const telemetry=[];
function mode(request){try{return new URL(request.headers.referer||'http://x/?mode=normal').searchParams.get('mode')||'normal'}catch{return 'normal'}}
function json(response,status,payload){response.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});response.end(JSON.stringify(payload))}
function asset(request,response){const current=mode(request),name=decodeURIComponent(new URL(request.url,'http://x').pathname.slice('/app/assets/'.length)),file=path.resolve(root,name);if((current==='main-404'&&name==='app.js')||!file.startsWith(root)||!fs.existsSync(file)){response.writeHead(404);return response.end()}if((current==='design-404'||current==='design-timeout')&&name==='EAGENT_DESIGN_TOKENS.json'){if(current==='design-timeout')return;response.writeHead(404);return response.end()}if(current==='main-wrong-mime'&&name==='app.js'){response.writeHead(200,{'Content-Type':'text/html','X-Content-Type-Options':'nosniff'});return response.end('window.shouldNotRun=true')}if(current==='early-js-error'&&name==='app.js'){response.writeHead(200,{'Content-Type':'application/javascript'});return response.end('throw new Error("early boot test")')}if(current==='screens-init-failure'&&name==='screens.js'){response.writeHead(200,{'Content-Type':'application/javascript'});return response.end('throw new Error("screens init test")')}const type=name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.json')?'application/json':'application/octet-stream';response.writeHead(200,{'Content-Type':type,'X-Content-Type-Options':'nosniff'});if(name.endsWith('.js'))return response.end(fs.readFileSync(file,'utf8').replaceAll('__NOEMA_APP_BUILD_ID__',buildId));fs.createReadStream(file).pipe(response)}
const server=http.createServer((request,response)=>{
 const url=new URL(request.url,'http://127.0.0.1');
 if(url.pathname==='/app'||url.pathname==='/app/')return response.end(fs.readFileSync(path.join(root,'index.html'),'utf8').replaceAll('__NOEMA_APP_BUILD_ID__',buildId));
 if(url.pathname.startsWith('/app/assets/'))return asset(request,response);
 if(url.pathname==='/api/v1/miniapp/boot-telemetry'){let body='';request.on('data',chunk=>body+=chunk);request.on('end',()=>{try{telemetry.push(JSON.parse(body))}catch{}json(response,200,{ok:true})});return}
 if(url.pathname==='/api/v1/miniapp/voice/transcribe'){request.on('end',()=>{const key='voice-transcribe',count=(attempts.get(key)||0)+1;attempts.set(key,count);if(count===1)return json(response,503,{ok:false,error:'Распознавание временно недоступно.',code:'STT_ERROR'});return json(response,200,{ok:true,data:{text:'повторная реплика'}})});request.resume();return}
 if(url.pathname==='/api/v1/miniapp'){let body='';request.on('data',chunk=>body+=chunk);request.on('end',()=>{const current=mode(request),payload=JSON.parse(body||'{}');if(payload.action==='state'){
   if(current==='timeout')return;
   if(current==='auth')return json(response,401,{ok:false});
   if(current==='retry'){const count=(attempts.get(current)||0)+1;attempts.set(current,count);if(count===1)return json(response,401,{ok:false})}
   return json(response,200,{ok:true,data:state});
  }if(current==='widget-failure'&&(payload.action==='budget'||payload.action==='weather'))return json(response,503,{ok:false});return json(response,200,{ok:true,data:{items:[],currency_totals:{},city:'',current:null}})});return}
 response.writeHead(404);response.end();
});
const check=(value,message)=>{if(!value)throw new Error(message)};
async function open(browser,base,modeName){
 const context=await browser.newContext({viewport:{width:390,height:844}});
 if(modeName==='voice-barge')await context.addInitScript(()=>{
  Object.defineProperty(navigator,'userAgent',{configurable:true,value:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)'});
  window.__micCalls=0;window.__trackStops=0;
  const stream={getTracks:()=>[{stop(){window.__trackStops++}}]};
  Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:async()=>{window.__micCalls++;return stream}}});
  class FakeMediaRecorder{
   static isTypeSupported(){return true}
   constructor(input,options={}){this.stream=input;this.mimeType=options.mimeType||'audio/mp4';this.state='inactive'}
   start(){this.state='recording'}
   stop(){if(this.state!=='recording')return;this.state='inactive';this.ondataavailable?.({data:new Blob(['voice'],{type:this.mimeType})});queueMicrotask(()=>this.onstop?.())}
  }
  Object.defineProperty(window,'MediaRecorder',{configurable:true,value:FakeMediaRecorder});
 });
 await context.route('https://telegram.org/js/telegram-web-app.js',route=>route.fulfill({contentType:'application/javascript',body:`
  const boot=()=>window.Telegram={WebApp:{initData:'signed',platform:'ios',version:'8.0',ready(){},expand(){},setHeaderColor(){},setBackgroundColor(){},onEvent(){},BackButton:{show(){},hide(){},onClick(){}}}};
  const mode=new URL(location.href).searchParams.get('mode');if(mode==='sdk-delayed')setTimeout(boot,250);else if(mode==='sdk-delayed-raw')setTimeout(boot,4000);else if(mode==='initdata-missing')window.Telegram={WebApp:{platform:'ios',version:'8.0'}};else if(mode!=='sdk-missing'&&mode!=='sdk-missing-raw')boot();
 `}));
 const page=await context.newPage();page.setDefaultTimeout(12000);if(modeName==='optional-api-missing')await page.addInitScript(()=>{delete window.ResizeObserver;delete window.IntersectionObserver;delete window.visualViewport});const raw=['sdk-delayed-raw','sdk-missing-raw'].includes(modeName)?'#tgWebAppData=signed':'';await page.goto(`${base}/app?mode=${modeName}${raw}`,{waitUntil:'domcontentloaded'});return {context,page};
}
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://lvh.me:${server.address().port}`,browser=await browserType.launch({headless:true});
 try{
  let telemetryBefore=telemetry.length,session=await open(browser,base,'normal');await session.page.locator('#splash.hidden').waitFor();check(await session.page.locator('#content .hero').count()===1,'A: normal boot did not render Home');check((await session.page.evaluate(()=>window.NoemaBootEvents.map(event=>event.stage))).includes('APP_READY'),'A: normal boot did not reach APP_READY');await session.page.waitForTimeout(100);check(telemetry.length===telemetryBefore,'A: successful boot emitted failure telemetry');await session.context.close();
  session=await open(browser,base,'sdk-delayed');await session.page.locator('#splash.hidden').waitFor();check(await session.page.locator('#content .hero').count()===1,'B: delayed SDK did not recover');await session.context.close();
  for(const fallbackMode of ['sdk-delayed-raw','sdk-missing-raw']){session=await open(browser,base,fallbackMode);await session.page.locator('#splash.hidden').waitFor();check(await session.page.locator('#content .hero').count()===1,`${fallbackMode}: raw signed init data did not boot Home`);await session.context.close()}
  for(const degraded of ['sdk-missing','initdata-missing']){session=await open(browser,base,degraded);await session.page.locator('#splash.hidden').waitFor({timeout:6000});check(await session.page.locator('#content .hero').count()===1,`${degraded}: Telegram startup issue blocked Home`);check(await session.page.locator('#boot-recovery:not([hidden])').count()===0,`${degraded}: recoverable Telegram issue opened fatal recovery`);await session.context.close()}
  for(const failure of ['main-404','main-wrong-mime','early-js-error']){session=await open(browser,base,failure);await session.page.locator('#boot-recovery:not([hidden])').waitFor();await session.page.waitForTimeout(100);check(await session.page.locator('#splash.hidden').count()===1,`${failure}: splash remained active`);await session.context.close()}
  session=await open(browser,base,'optional-api-missing');await session.page.locator('#splash.hidden').waitFor();check(await session.page.locator('#content .hero').count()===1,'G: optional APIs blocked Home');await session.context.close();
  for(const designMode of ['design-404','design-timeout']){session=await open(browser,base,designMode);await session.page.locator('#splash.hidden').waitFor();check(await session.page.locator('#content .hero').count()===1,`${designMode}: optional design tokens blocked Home`);const fallbackStyle=await session.page.evaluate(()=>({ink:getComputedStyle(document.documentElement).getPropertyValue('--ink').trim().toLowerCase(),color:getComputedStyle(document.body).color}));check(fallbackStyle.ink==='#f4f4f2'&&fallbackStyle.color!=='rgb(0, 0, 0)',`${designMode}: token failure made rendered Home invisible ${JSON.stringify(fallbackStyle)}`);await session.context.close()}
  session=await open(browser,base,'auth');await session.page.locator('#splash.hidden').waitFor();await session.page.locator('#notice.visible').waitFor();check(await session.page.locator('#content .hero').count()===1,'D: auth 401 blocked Home');check((await session.page.locator('#notice').textContent()).includes('Telegram'),'D: auth retry status missing');check(await session.page.locator('#boot-recovery:not([hidden])').count()===0,'D: auth 401 opened fatal recovery');await session.context.close();
  session=await open(browser,base,'widget-failure');await session.page.locator('#splash.hidden').waitFor();check(await session.page.locator('#content .hero').count()===1,'E: a failed widget blocked Home');await session.context.close();
  attempts.clear();session=await open(browser,base,'retry');await session.page.locator('#splash.hidden').waitFor();await session.page.waitForTimeout(1600);check((attempts.get('retry')||0)>=2,'I: transient state/auth failure was not retried automatically');check(await session.page.locator('#content .hero').count()===1,'I: automatic retry did not keep Home available');check(await session.page.locator('#boot-recovery:not([hidden])').count()===0,'I: transient state failure opened fatal recovery');await session.context.close();
  attempts.delete('voice-transcribe');session=await open(browser,base,'voice-barge');await session.page.locator('#splash.hidden').waitFor();const barge=await session.page.evaluate(async()=>{const controller=window.NoemaVoiceController;let cancelled=0,paused=0,resumed=0,asked='';controller.speech.pause=()=>paused++;controller.speech.resume=()=>resumed++;controller.speech.cancel=()=>cancelled++;controller.ask=async text=>{asked=text;controller.setState('idle')};controller.setState('speaking');await controller.toggle();const afterTap=controller.state;await controller.toggle();const afterSecondTap=controller.state;controller.setState('speaking');await controller.bargeIn();const afterHold=controller.state;controller.stopRecording();for(let index=0;index<100&&!asked;index++)await new Promise(resolve=>setTimeout(resolve,20));return {afterTap,afterSecondTap,afterHold,paused,resumed,cancelled,asked,micCalls:window.__micCalls,trackStops:window.__trackStops}});check(barge.afterTap==='paused'&&barge.afterSecondTap==='speaking'&&barge.paused===1&&barge.resumed===1&&barge.micCalls===1,'V: tap pause/resume or hold-to-record contract is broken');check(barge.afterHold==='recording'&&barge.cancelled===1,'V: hold during speech did not start a fresh recording');check(barge.asked==='повторная реплика'&&(attempts.get('voice-transcribe')||0)===2&&barge.trackStops>=1,'V: transient transcription did not recover from the same isolated recording');await session.context.close();
  session=await open(browser,base,'normal');await session.page.locator('#splash.hidden').waitFor();await session.page.evaluate(()=>window.NoemaBoot.assetReady('app.js','old-build'));await session.page.waitForURL(/__noema_build=/);await session.page.evaluate(()=>window.NoemaBoot.assetReady('app.js','old-build'));await session.page.locator('#boot-recovery:not([hidden])').waitFor();check(await session.page.evaluate(()=>sessionStorage.getItem('noema-build-reload:'+window.NoemaBoot.APP_BUILD_ID)==='1'),'F: mismatch reload was not limited');await session.context.close();
  telemetryBefore=telemetry.length;session=await open(browser,base,'timeout');const slowStarted=Date.now();await session.page.locator('#splash.hidden').waitFor({timeout:3000});check(Date.now()-slowStarted<3000,'C: slow state request blocked first paint');check(await session.page.locator('#content .hero').count()===1,'C: slow state request did not render Home');check(await session.page.locator('#boot-recovery:not([hidden])').count()===0,'C: slow state request opened fatal recovery');check(telemetry.length===telemetryBefore,'C: non-fatal state delay emitted boot-failure telemetry');await session.context.close();
  telemetryBefore=telemetry.length;session=await open(browser,base,'screens-init-failure');await session.page.locator('#boot-recovery:not([hidden])').waitFor();await session.page.waitForTimeout(100);check(telemetry.length===telemetryBefore+1&&telemetry[telemetry.length-1].last_boot_stage==='SCREENS_INIT','E: screens init failure did not report SCREENS_INIT');await session.context.close();
  console.log(JSON.stringify({MINIAPP_BOOT_BROWSER:'PASS',browser:browserName,telemetry_events:telemetry.length},null,2));
 }finally{await browser.close();server.close()}
})().catch(error=>{console.error(error);server.close();process.exitCode=1});
