const tg=window.Telegram?.WebApp;
const content=document.querySelector('#content'),notice=document.querySelector('#notice');
const emptyState=()=>({day:new Date().toLocaleDateString('en-CA'),plan:{tasks:[],reminders:[]},tasks:[],reminders:[],notes:[],people:[],expenses:[],files:[],history:[],rules:[],settings:{mode:'text',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,briefing:{enabled:false,time:'08:30',topics:'главные новости мира',city:''}}});
let data=emptyState(),page='home',filter='all',search='',busy=false;
const {icon,iconButton,segmented}=NoemaUI;
const defaultWidgets=['tasks','next_event','notes','reminders','budget','recent_saved'];
const widgetNames={tasks:'Задачи',next_event:'Ближайшее',notes:'Заметки',reminders:'Напоминания',budget:'Бюджет',recent_saved:'Недавно сохранено',people:'Люди'};
let weatherData=null,monthBudget=null,taskTab='today',navHistory=[],layoutDraft=[],archiveResults=null;
const preview=!tg?.initData;
const telemetry=window.NoemaTelemetry=window.NoemaTelemetry||{events:[],latest:{}};
telemetry.record=telemetry.record||function(name,value,detail={}){const sample={name,value:Math.max(0,Math.round(Number(value)||0)),at:Date.now(),...detail};this.latest[name]=sample;this.events.push(sample);if(this.events.length>80)this.events.splice(0,this.events.length-80);return sample};
let lagExpected=performance.now()+2000;
setInterval(()=>{const current=performance.now(),lag=Math.max(0,current-lagExpected);lagExpected=current+2000;if(!document.hidden)telemetry.record('event_loop_lag_ms',lag)},2000);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(Number(v)||0);
const date=v=>v?new Date(v).toLocaleDateString('ru-RU',{day:'numeric',month:'long'}):'Без даты';
function say(message){notice.textContent=message;notice.classList.toggle('visible',!!message)}
async function api(action,args={}){
  if(preview)throw Error('Для сохранения открой Noema через Telegram. Здесь доступен только просмотр оформления.');
  const started=performance.now();
  try{const response=await fetch('/api/v1/miniapp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({init_data:tg.initData,action,args})});
   if(response.status===401)throw Error('Сессия закончилась. Закрой и снова открой приложение в Telegram.');
   const result=await response.json();if(!response.ok||!result.ok)throw Error(result.error||'Нет соединения с Noema.');return result.data}
  finally{telemetry.record('ui_action_ms',performance.now()-started,{action})}
}
async function load(){data=await api('state');render()}
function empty(text='Здесь пока тихо. Добавь первую запись.'){return `<div class="empty">${text}</div>`}
function card(title,body,target,name){return NoemaUI.card(title,body,target,name)}
function taskRows(items){return items.map(t=>`<div class="row"><button class="check ${t.status!=='open'?'done':''}" data-toggle="${t.id}" aria-label="Изменить статус задачи">${t.status!=='open'?'✓':''}</button><div class="body"><p>${esc(t.text)}</p><small>${date(t.due_date)}</small></div>${page==='tasks'?`<button class="delete" data-delete="delete_task" data-id="${t.id}" aria-label="Удалить задачу">×</button>`:''}</div>`).join('')||empty('Планы свободны. Чем займёмся?')}
function home(){
  const d=new Date(data.day+'T12:00:00');
  const pending=data.tasks.filter(t=>t.status==='open'&&(!t.due_date||t.due_date<=data.day));
  const upcoming=data.reminders.filter(r=>!r.acknowledged).sort((a,b)=>a.remind_at_utc.localeCompare(b.remind_at_utc))[0];
  const spent=data.expenses.filter(e=>e.kind!=='income').reduce((s,e)=>s+Number(e.amount),0);
  return `<section class="card hero"><div class="hero-content"><h3>ТВОЙ ДЕНЬ</h3><div class="hero-date"><span class="date-number">${d.getDate()}</span><p>${d.toLocaleDateString('ru-RU',{month:'long'})}<br>${d.toLocaleDateString('ru-RU',{weekday:'long'})}</p></div><p class="subtle" style="margin:18px 0 0">${pending.length?pending.length+' дел ждут твоего внимания':'Немного пространства для себя'}</p></div><div class="ambient-orb"></div></section>
  <div class="grid">${card('Задачи',taskRows(pending.slice(0,3)),'tasks')}${card('Следующее напоминание',upcoming?`<p class="amount">${new Date(upcoming.remind_at_utc).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',timeZone:data.settings.timezone})}</p><p>${esc(upcoming.text)}</p><small>${date(upcoming.remind_at_utc)}</small>`:empty('Никаких сигналов. Всё спокойно.'),'reminders')}${card('Заметки',data.notes.slice(0,3).map(n=>`<p>${esc(n.title||n.text.slice(0,85))}</p>`).join('')||empty('Сохрани мысль — я запомню.'),'archive')}${card('Бюджет',`<small>Расходы · доступная история</small><p class="amount">${money(spent)}</p><small>${data.expenses.length} операций</small>`,'budget')}</div>`;
}
function archive(){
  const sources=[...data.notes.map(n=>({...n,type:'notes',label:'Заметка',name:n.title||n.text})),...data.files.map(f=>({...f,type:'files',label:f.mime_type?.startsWith('image/')?'Изображение':'Файл',name:f.original_name,text:f.summary}))];
  const items=sources.filter(x=>(filter==='all'||filter===x.type)&&`${x.name} ${x.text}`.toLowerCase().includes(search.toLowerCase()));
  return `<h1>Архив</h1><p class="subtle">Всё, что стоит сохранить.</p><input class="search" id="search" placeholder="Найти в заметках и файлах…" value="${esc(search)}"><div class="toolbar">${[['all','Всё'],['notes','Заметки'],['files','Файлы']].map(([key,label])=>`<button class="pill ${filter===key?'selected':''}" data-filter="${key}">${label}</button>`).join('')}<button class="secondary" data-form="note">＋ Заметка</button></div>${items.map(n=>`<article class="card"><div class="card-head"><h2>${esc(n.name?.slice(0,100))}</h2>${n.type==='notes'?`<button class="delete" data-delete="delete_note" data-id="${n.id}" aria-label="Удалить заметку">×</button>`:''}</div><p class="subtle">${esc(n.text)}</p><small>${n.label} · ${date(n.created_at)}</small></article>`).join('')||empty()}`;
}
function people(){return `<h1>Люди</h1><p class="subtle">Noema помнит важное о людях.</p><div class="toolbar"><button class="secondary" data-form="person">＋ Добавить человека</button></div>${data.people.map(p=>`<details class="card"><summary class="row"><span class="avatar">${esc(p.name?.[0])}</span><div class="body"><h2 style="margin:0">${esc(p.name)}</h2><small>${esc(p.relationship||'Знакомый')}</small></div></summary><div class="details"><h3>Что важно</h3><p>${esc(p.notes||'Пока нет заметок')}</p>${p.projects?`<p>Проекты: ${esc(p.projects)}</p>`:''}${p.birthday?`<p>День рождения: ${esc(p.birthday)}</p>`:''}<h3>Недавние упоминания</h3>${p.recent_interactions.map(i=>`<p>${esc(i.interaction)}<br><small>${esc(i.interaction_date)}</small></p>`).join('')||'<p>Пока нет упоминаний</p>'}<button class="secondary" data-delete="delete_person" data-id="${p.id}">Удалить человека</button></div></details>`).join('')||empty()}`}
function tasks(){return `<h1>Задачи</h1><div class="toolbar"><button class="primary" data-form="task">＋ Добавить</button></div>${card('Предстоящие',taskRows(data.tasks.filter(t=>t.status==='open')))}${card('Выполнено',taskRows(data.tasks.filter(t=>t.status!=='open')))}`}
function reminders(){return `<h1>Напоминания</h1><div class="toolbar"><button class="primary" data-form="reminder">＋ Напомнить</button></div>${data.reminders.map(r=>`<article class="card row"><button class="check ${r.acknowledged?'done':''}" data-reminder="${r.id}" ${r.acknowledged?'disabled':''} aria-label="Выполнить напоминание">${r.acknowledged?'✓':''}</button><div class="body"><p>${esc(r.text)}</p><small>${new Date(r.remind_at_utc).toLocaleString('ru-RU',{timeZone:data.settings.timezone})}</small></div><button class="delete" data-delete="delete_reminder" data-id="${r.id}" aria-label="Удалить напоминание">×</button></article>`).join('')||empty()}`}
function budget(){return `<h1>Бюджет</h1><div class="toolbar"><button class="primary" data-form="expense">＋ Расход</button><button class="secondary" data-form="income">＋ Доход</button></div>${card('Баланс доступной истории',`<p class="amount">${money(data.expenses.reduce((s,e)=>s+(e.kind==='income'?1:-1)*Number(e.amount),0))}</p>`)}${data.expenses.map(e=>`<article class="card row"><div class="body"><p>${esc(e.description)}</p><small>${date(e.spent_at)} · ${esc(e.category)}</small></div><span>${e.kind==='income'?'+':'−'}${money(e.amount)}</span><button data-delete="delete_expense" data-id="${e.id}" aria-label="Удалить операцию">×</button></article>`).join('')||empty()}`}
function settings(){const s=data.settings,b=s.briefing;return `<h1>Настройки</h1><p class="subtle">Фокус, ясность и контроль.</p>${card('Аккаунт',`<div class="setting"><label>Часовой пояс</label><button data-form="timezone">${esc(s.timezone)} ›</button></div><div class="setting"><label>Режим ответов в Telegram</label><select id="mode">${[['text','Текст'],['voice','Голос'],['voice_and_text','Голос + текст']].map(([k,v])=>`<option value="${k}" ${s.mode===k?'selected':''}>${v}</option>`).join('')}</select></div>`)}${card('Утренний брифинг',`<div class="setting"><label for="brief-enabled">Присылать каждый день</label><input id="brief-enabled" type="checkbox" ${b.enabled?'checked':''}></div><div class="setting"><label for="brief-time">По местному времени</label><input id="brief-time" type="time" value="${esc(b.time)}"></div><div class="setting"><label>Темы и город</label><button data-form="briefing">Настроить ›</button></div><small>${esc(b.topics)}</small>`)}${card('Правила',`${data.rules.map(r=>`<div class="row"><div class="body">${esc(r.description)}</div><button data-delete="delete_behavior_rule" data-id="${r.id}" aria-label="Удалить правило">×</button></div>`).join('')}<button class="secondary" data-form="rule">＋ Новое правило</button>`)}${card('Память',`<p class="subtle">Можно очистить историю диалога. Заметки, люди и планы сохранятся.</p><button class="secondary" id="clear-chat">Очистить диалог</button>`)}<p class="subtle">Подключение iPhone и управление AI доступны в настройках бота.</p>`}
function chat(){return `<h1>Я рядом</h1><p class="subtle">Спроси, расскажи или сохрани мысль.</p><div class="chat">${data.history.map(m=>`<div class="bubble ${m.role==='user'?'user':'assistant'}">${esc(m.content)}</div>`).join('')||empty('«Напомни завтра позвонить маме»<br>«Запиши 350 рублей на кофе»')}<div id="thinking" class="subtle" hidden>Обдумываю…</div></div><form id="chat-form" class="composer"><input id="chat-input" autocomplete="off" placeholder="Спроси Noema…" required maxlength="12000"><button aria-label="Отправить" type="submit">↑</button></form>`}
function render(){content.innerHTML=({home,archive,people,tasks,reminders,budget,settings,chat}[page]||home)();const orb=content.querySelector('.ambient-orb');if(orb)orb.outerHTML='<canvas class="membrane" width="500" height="500" aria-hidden="true"></canvas>';if(page==='chat'){const mic=document.createElement('button');mic.type='button';mic.id='record';mic.textContent='◎';mic.setAttribute('aria-label','Записать голосовое сообщение');content.querySelector('.composer').prepend(mic)}document.querySelectorAll('nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(tg){page==='home'?tg.BackButton.hide():tg.BackButton.show()}}
function go(next){page=next;search='';filter='all';render();window.scrollTo({top:0})}
const forms={task:['Новая задача','add_task',[['text','Что сделать','textarea'],['due_date','Дата','date'],['priority','Приоритет','text']]],note:['Сохранить мысль','save_note',[['title','Заголовок','text'],['text','Заметка','textarea']]],reminder:['Напомнить','set_reminder',[['text','О чём напомнить','textarea'],['remind_at','Когда · '+data.settings.timezone,'datetime-local']]],expense:['Новый расход','add_expense',[['amount','Сумма в рублях','number'],['description','На что потрачено','text'],['category','Категория','text']]],income:['Новое поступление','add_income',[['amount','Сумма в рублях','number'],['description','Источник','text'],['category','Категория','text']]],person:['Новый человек','person_upsert',[['name','Имя','text'],['relationship','Кто это для тебя','text'],['birthday','День рождения','date'],['projects','Проекты','text'],['notes','Что важно','textarea']]],rule:['Новое правило','save_behavior_rule',[['description','Как мне отвечать и помогать','textarea']]],timezone:['Часовой пояс','set_timezone',[['timezone_name','Например Europe/Moscow','text']]],briefing:['Твой брифинг','set_briefing_preferences',[['topics','Интересные темы','text'],['city','Город для погоды','text']]]};
let editAction='';
let recorder=null;
function voiceControl(button,recording){button.setAttribute('aria-label',recording?'Закончить запись':'Начать голосовой запрос');if(button.id==='record')button.innerHTML=recording?'■':icon('mic');document.querySelector('#voice-status')?.replaceChildren(document.createTextNode(recording?'Слушаю · нажми, чтобы закончить':'Нажми, чтобы говорить'))}
async function recordVoice(button){
  if(recorder?.state==='recording'){recorder.stop();return}
  if(busy)return;
  if(preview){say('Голос доступен при открытии через Telegram.');return}
  busy=true;
  let stream;
  try{
    stream=await navigator.mediaDevices.getUserMedia({audio:true});
    const mime=['audio/webm','audio/mp4'].find(x=>MediaRecorder.isTypeSupported(x));
    recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{});const chunks=[];
    const audioContext=new AudioContext(),analyser=audioContext.createAnalyser();analyser.fftSize=256;audioContext.createMediaStreamSource(stream).connect(analyser);const samples=new Uint8Array(analyser.frequencyBinCount);
    const meter=setInterval(()=>{analyser.getByteTimeDomainData(samples);let sum=0;for(const x of samples)sum+=((x-128)/128)**2;NoemaMembrane.setAudioLevel(Math.min(1,Math.sqrt(sum/samples.length)*4))},60);
    NoemaMembrane.setState('listening');
    recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};
    recorder.onstop=async()=>{
      clearTimeout(timer);clearInterval(meter);audioContext.close();stream.getTracks().forEach(t=>t.stop());voiceControl(button,false);busy=true;NoemaMembrane.setState('thinking');say('Обдумываю…');
      try{const form=new FormData();form.append('init_data',tg.initData);form.append('audio',new Blob(chunks,{type:recorder.mimeType}),'voice');const response=await fetch('/api/v1/miniapp/voice',{method:'POST',body:form});if(!response.ok)throw Error('Не удалось обработать голос. Попробуй ещё раз.');await load();say('');NoemaMembrane.setState('responding')}catch(e){say(e.message);NoemaMembrane.setState('muted')}finally{busy=false;recorder=null}
    };
    recorder.start();voiceControl(button,true);say('Слушаю. Нажми на сферу ещё раз, чтобы отправить запись.');const timer=setTimeout(()=>{if(recorder?.state==='recording')recorder.stop()},120000);
  }catch(e){busy=false;stream?.getTracks().forEach(t=>t.stop());recorder=null;NoemaMembrane.setState('muted');say('Не удалось включить микрофон. Проверь разрешение Telegram или браузера.')}
}
function openForm(name,values={},actionOverride='',titleOverride=''){const [title,action,fields]=forms[name];editAction=actionOverride||action;document.querySelector('#form-title').textContent=titleOverride||title;const fieldKeys=new Set(fields.map(x=>x[0]));const hidden=Object.entries(values).filter(([key])=>key.endsWith('_id')&&!fieldKeys.has(key)).map(([key,value])=>`<input type="hidden" name="${key}" value="${esc(value)}">`).join('');document.querySelector('#fields').innerHTML=fields.map(([key,label,type])=>{const value=values[key]??(name==='timezone'?data.settings.timezone:name==='briefing'?data.settings.briefing[key]||'':key==='priority'?'normal':'');const optional=['relationship','notes','due_date','city','title','birthday','projects','category','priority'].includes(key);return `<label>${esc(label)}${type==='textarea'?`<textarea name="${key}" ${optional?'':'required'}>${esc(value)}</textarea>`:`<input name="${key}" type="${type}" ${type==='number'?'min="0.01" step="0.01"':''} value="${esc(value)}" ${optional?'':'required'}>`}</label>`}).join('')+hidden;document.querySelector('#editor').showModal()}
function localDateTime(value){if(!value)return '';const d=new Date(value);const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function openEdit(type,id){let item,values,action,title,form;if(type==='task'){item=data.tasks.find(x=>x.id===id);values={text:item?.text,due_date:item?.due_date,priority:item?.priority,task_id:id};action='update_task';title='Изменить задачу';form='task'}if(type==='note'){item=data.notes.find(x=>x.id===id);values={title:item?.title,text:item?.text,note_id:id};action='update_note';title='Изменить заметку';form='note'}if(type==='reminder'){item=data.reminders.find(x=>x.id===id);values={text:item?.text,remind_at:localDateTime(item?.remind_at_utc),reminder_id:id};action='update_reminder';title='Изменить напоминание';form='reminder'}if(type==='expense'){item=(budgetData?.items||data.expenses).find(x=>x.id===id);values={amount:item?.amount,description:item?.description,category:item?.category,expense_id:id};action='update_expense';title='Изменить операцию';form=item?.kind==='income'?'income':'expense'}if(type==='person'){item=data.people.find(x=>x.id===id);values={name:item?.name,relationship:item?.relationship,birthday:item?.birthday,projects:item?.projects,notes:item?.notes,person_id:id};action='update_person';title='Изменить человека';form='person'}if(type==='rule'){item=data.rules.find(x=>x.id===id);values={description:item?.description,rule_id:id};action='update_behavior_rule';title='Изменить правило';form='rule'}if(item)openForm(form,values,action,title)}
async function mutate(action,args){if(busy)return;busy=true;try{await api(action,args);await load();if(page==='budget')await loadBudget();say('')}catch(e){say(e.message)}finally{busy=false}}
document.addEventListener('click',async e=>{const b=e.target.closest('button,[role=button]');if(!b)return;
  if(b.dataset.page)go(b.dataset.page);
  if(b.id==='record')await recordVoice(b);
  if(b.dataset.filter){filter=b.dataset.filter;render()}
  if(b.dataset.form)openForm(b.dataset.form);
  if(b.dataset.edit)openEdit(b.dataset.edit,Number(b.dataset.id));
  if(b.dataset.toggle)await mutate('task_toggle',{id:Number(b.dataset.toggle)});
  if(b.dataset.reminder)await mutate('reminder_done',{id:Number(b.dataset.reminder)});
  if(b.dataset.delete&&confirm('Удалить эту запись?')){const keys={delete_note:'note_id',delete_task:'task_id',delete_person:'person_id',delete_expense:'expense_id',delete_reminder:'reminder_id',delete_behavior_rule:'rule_id'};await mutate(b.dataset.delete,{[keys[b.dataset.delete]]:Number(b.dataset.id)})}
  if(b.id==='cancel')document.querySelector('#editor').close();
  if(b.id==='clear-chat'&&confirm('Очистить историю диалога?'))await mutate('clear_history',{});
});
document.addEventListener('change',async e=>{if(e.target.id==='mode')await mutate('mode',{mode:e.target.value});if(e.target.id==='brief-enabled')await mutate('set_briefing_preferences',{enabled:e.target.checked});if(e.target.id==='brief-time')await mutate('set_briefing_preferences',{time:e.target.value})});
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;search=e.target.value;render();const input=document.querySelector('#search');input.focus();input.setSelectionRange(pos,pos)}});
document.querySelector('#edit-form').addEventListener('submit',async e=>{e.preventDefault();const args=Object.fromEntries(new FormData(e.target));if(args.amount)args.amount=Number(args.amount);await mutate(editAction,args);if(!notice.textContent)document.querySelector('#editor').close()});
async function streamChat(text,options={}){const response=await fetch('/api/v1/miniapp/chat-stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({init_data:tg?.initData||'',text}),signal:options.signal});if(!response.ok)throw Error(await response.text()||'Не удалось получить ответ.');const thread=document.querySelector('.chat'),thinking=document.querySelector('#thinking');let bubble=null;if(thread){bubble=document.createElement('div');bubble.className='bubble assistant streaming';(thinking||thread).before?.(bubble)}const reader=response.body.getReader(),decoder=new TextDecoder();let pending='',answer='';while(true){const {value,done}=await reader.read();pending+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=pending.split('\n');pending=lines.pop()||'';for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==='delta'){answer+=event.text;if(bubble)bubble.textContent+=event.text;if(thread)thread.scrollTop=thread.scrollHeight;options.onDelta?.(event.text)}if(event.type==='cancelled')throw new DOMException('Generation stopped','AbortError');if(event.type==='error')throw Error('Не удалось получить ответ. Попробуй ещё раз.')}if(done)break}return answer}
document.addEventListener('submit',async e=>{if(e.target.id!=='chat-form')return;e.preventDefault();if(busy)return;const input=document.querySelector('#chat-input'),text=input.value.trim();if(!text)return;busy=true;input.value='';document.querySelector('#thinking').hidden=false;try{await streamChat(text);await load();say('')}catch(err){say(err.message);input.value=text}finally{busy=false;const thinking=document.querySelector('#thinking');if(thinking)thinking.hidden=true}});
// Bootstrapping and screen composition live in screens.js.
