const tg=window.Telegram?.WebApp;
const content=document.querySelector('#content'),notice=document.querySelector('#notice');
const emptyState=()=>({day:new Date().toLocaleDateString('en-CA'),plan:{tasks:[],reminders:[]},tasks:[],reminders:[],notes:[],people:[],expenses:[],files:[],history:[],rules:[],settings:{mode:'text',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,briefing:{enabled:false,time:'08:30',topics:'главные новости мира',city:''}}});
let data=emptyState(),page='home',filter='all',search='',busy=false;
const {icon,iconButton,segmented}=NoemaUI;
const defaultWidgets=['tasks','next_event','notes','reminders','budget','recent_saved'];
const widgetNames={tasks:'Задачи',next_event:'Ближайшее',notes:'Заметки',reminders:'Напоминания',budget:'Бюджет',recent_saved:'Недавно сохранено',people:'Люди'};
let weatherData=null,monthBudget=null,taskTab='today',navHistory=[],layoutDraft=[],archiveResults=null,statusMessage='',stateLoadedAt=0,stateRefreshPromise=null,homeEditing=false;
const preview=!tg?.initData;
const telemetry=window.NoemaTelemetry=window.NoemaTelemetry||{events:[],latest:{}};
telemetry.record=telemetry.record||function(name,value,detail={}){const sample={name,value:Math.max(0,Math.round(Number(value)||0)),at:Date.now(),...detail};this.latest[name]=sample;this.events.push(sample);if(this.events.length>80)this.events.splice(0,this.events.length-80);return sample};
let lagExpected=performance.now()+2000;
setInterval(()=>{const current=performance.now(),lag=Math.max(0,current-lagExpected);lagExpected=current+2000;if(!document.hidden)telemetry.record('event_loop_lag_ms',lag)},2000);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(Number(v)||0);
const date=v=>v?new Date(v).toLocaleDateString('ru-RU',{day:'numeric',month:'long'}):'Без даты';
function say(message){
  statusMessage=String(message||'');
  const composerStatus=document.querySelector('#composer-status');
  if(page==='chat'&&composerStatus){
    composerStatus.textContent=statusMessage;
    composerStatus.hidden=!statusMessage;
    notice.textContent='';notice.classList.remove('visible');
    return;
  }
  notice.textContent=statusMessage;notice.classList.toggle('visible',!!statusMessage)
}
async function api(action,args={}){
  if(preview)throw Error('Для сохранения открой Noema через Telegram. Здесь доступен только просмотр оформления.');
  const started=performance.now();
  try{const response=await fetch('/api/v1/miniapp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({init_data:tg.initData,action,args})});
   if(response.status===401)throw Error('Сессия закончилась. Закрой и снова открой приложение в Telegram.');
   const result=await response.json();if(!response.ok||!result.ok)throw Error(result.error||'Нет соединения с Noema.');return result.data}
  finally{telemetry.record('ui_action_ms',performance.now()-started,{action})}
}
async function load(){data=await api('state');stateLoadedAt=Date.now();window.NoemaTelemetryEnabled=Boolean(data.settings?.telemetry_enabled);window.NoemaRealtimeBeta?.setEnabled(Boolean(data.settings?.experimental_realtime),{wakeEnabled:Boolean(data.settings?.experimental_wake_enabled)}).catch(()=>{});render()}
function refreshStateOnResume(){if(preview||document.hidden||!stateLoadedAt||Date.now()-stateLoadedAt<750||stateRefreshPromise)return;stateRefreshPromise=load().catch(()=>{}).finally(()=>{stateRefreshPromise=null})}
function empty(text='Здесь пока тихо. Добавь первую запись.'){return `<div class="empty">${text}</div>`}
function card(title,body,target,name){return NoemaUI.card(title,body,target,name)}
function taskRows(items){return items.map(t=>`<div class="row"><button class="check ${t.status!=='open'?'done':''}" data-toggle="${t.id}" aria-label="Изменить статус задачи">${t.status!=='open'?'✓':''}</button><div class="body"><p>${esc(t.text)}</p><small>${date(t.due_date)}</small></div>${page==='tasks'?`<button class="delete" data-delete="delete_task" data-id="${t.id}" aria-label="Удалить задачу">×</button>`:''}</div>`).join('')||empty('Планы свободны. Чем займёмся?')}
function home(){
  const d=new Date(data.day+'T12:00:00');
  const pending=data.tasks.filter(t=>t.status==='open'&&(!t.due_date||t.due_date<=data.day));
  const upcoming=data.reminders.filter(r=>!r.acknowledged).sort((a,b)=>a.remind_at_utc.localeCompare(b.remind_at_utc))[0];
  const spent=data.expenses.filter(e=>e.kind!=='income').reduce((s,e)=>s+Number(e.amount),0);
  return `<section class="card hero"><div class="hero-content"><h3>ТВОЙ ДЕНЬ</h3><div class="hero-date"><span class="date-number">${d.getDate()}</span><p>${d.toLocaleDateString('ru-RU',{month:'long'})}<br>${d.toLocaleDateString('ru-RU',{weekday:'long'})}</p></div><p class="subtle" style="margin:18px 0 0">${pending.length?pending.length+' дел ждут твоего внимания':'Немного пространства для себя'}</p></div><div class="ambient-orb"></div></section>
  <div class="grid">${card('Задачи',taskRows(pending.slice(0,3)),'tasks')}${card('Следующее напоминание',upcoming?`<p class="amount">${new Date(upcoming.remind_at_utc).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',timeZone:data.settings.timezone})}</p><p>${esc(upcoming.text)}</p><small>${date(upcoming.remind_at_utc)}</small>`:empty('Никаких сигналов. Всё спокойно.'),'reminders')}${card('Заметки',data.notes.slice(0,3).map(n=>`<p>${esc(n.title||n.text.slice(0,85))}</p>`).join('')||empty('Сохрани мысль — я запомню.'),'archive')}${card('Бюджет',`<small>Расходы · доступная история</small><p class="amount">${money(spent)}</p><small>${data.expenses.length} операций</small>`,'budget')}</div>`;
}
function archive(){
  const sources=[...data.notes.map(n=>({...n,type:'notes',label:'Заметка',name:n.title||n.text})),...data.files.map(f=>({...f,type:'files',label:f.mime_type?.startsWith('image/')?'Изображение':'Файл',name:f.original_name,text:f.summary}))];
  const items=sources.filter(x=>(filter==='all'||filter===x.type)&&`${x.name} ${x.text}`.toLowerCase().includes(search.toLowerCase()));
  return `<h1>Архив</h1><p class="subtle">Всё, что стоит сохранить.</p><input class="search" id="search" placeholder="Найти в заметках и файлах…" value="${esc(search)}"><div class="toolbar">${[['all','Всё'],['notes','Заметки'],['files','Файлы']].map(([key,label])=>`<button class="pill ${filter===key?'selected':''}" data-filter="${key}">${label}</button>`).join('')}<button class="secondary" data-form="note">＋ Заметка</button></div>${items.map(n=>`<article class="card"><div class="card-head"><h2>${esc(n.name?.slice(0,100))}</h2>${n.type==='notes'?`<button class="delete" data-delete="delete_note" data-id="${n.id}" aria-label="Удалить заметку">×</button>`:''}</div><p class="subtle">${esc(n.text)}</p><small>${n.label} · ${date(n.created_at)}</small></article>`).join('')||empty()}`;
}
function people(){return `<h1>Люди</h1><p class="subtle">Noema помнит важное о людях.</p><div class="toolbar"><button class="secondary" data-form="person">＋ Добавить человека</button></div>${data.people.map(p=>`<details class="card"><summary class="row"><span class="avatar">${esc(p.name?.[0])}</span><div class="body"><h2 style="margin:0">${esc(p.name)}</h2><small>${esc(p.relationship||'Знакомый')}</small></div></summary><div class="details"><h3>Что важно</h3><p>${esc(p.notes||'Пока нет заметок')}</p>${p.projects?`<p>Проекты: ${esc(p.projects)}</p>`:''}${p.birthday?`<p>День рождения: ${esc(p.birthday)}</p>`:''}<h3>Недавние упоминания</h3>${p.recent_interactions.map(i=>`<p>${esc(i.interaction)}<br><small>${esc(i.interaction_date)}</small></p>`).join('')||'<p>Пока нет упоминаний</p>'}<button class="secondary" data-delete="delete_person" data-id="${p.id}">Удалить человека</button></div></details>`).join('')||empty()}`}
function tasks(){return `<h1>Задачи</h1><div class="toolbar"><button class="primary" data-form="task">＋ Добавить</button></div>${card('Предстоящие',taskRows(data.tasks.filter(t=>t.status==='open')))}${card('Выполнено',taskRows(data.tasks.filter(t=>t.status!=='open')))}`}
function reminders(){return `<h1>Напоминания</h1><div class="toolbar"><button class="primary" data-form="reminder">＋ Напомнить</button></div>${data.reminders.map(r=>`<article class="card row"><button class="check ${r.acknowledged?'done':''}" data-reminder="${r.id}" ${r.acknowledged?'disabled':''} aria-label="Выполнить напоминание">${r.acknowledged?'✓':''}</button><div class="body"><p>${esc(r.text)}</p><small>${new Date(r.remind_at_utc).toLocaleString('ru-RU',{timeZone:data.settings.timezone})}</small></div><button class="delete" data-delete="delete_reminder" data-id="${r.id}" aria-label="Удалить напоминание">×</button></article>`).join('')||empty()}`}
function budget(){return `<h1>Бюджет</h1><div class="toolbar"><button class="primary" data-form="expense">＋ Расход</button><button class="secondary" data-form="income">＋ Доход</button></div>${card('Баланс доступной истории',`<p class="amount">${money(data.expenses.reduce((s,e)=>s+(e.kind==='income'?1:-1)*Number(e.amount),0))}</p>`)}${data.expenses.map(e=>`<article class="card row"><div class="body"><p>${esc(e.description)}</p><small>${date(e.spent_at)} · ${esc(e.category)}</small></div><span>${e.kind==='income'?'+':'−'}${money(e.amount)}</span><button data-delete="delete_expense" data-id="${e.id}" aria-label="Удалить операцию">×</button></article>`).join('')||empty()}`}
function betaSettings(s){if(!s.experimental_realtime_available)return '';const beta=Boolean(s.experimental_realtime),wake=Boolean(s.experimental_wake_enabled);return card('Experimental · Beta',`<div class="setting"><label for="realtime-beta">Разговор</label><input id="realtime-beta" type="checkbox" ${beta?'checked':''}></div>${beta?`<div class="setting"><label for="wake-word-beta">Wake word «Эма»</label><input id="wake-word-beta" type="checkbox" ${wake?'checked':''}></div><button class="secondary" type="button" data-realtime-conversation><span>Разговор</span></button>`:'<small>Экспериментальный realtime-режим. Обычная сфера использует стабильное пакетное распознавание.</small>'}`)}
const runtimeConfigLabels={fast_model:'FAST model',fast_model_providers:'FAST providers',fast_model_allow_provider_fallback:'FAST provider fallback',strong_model:'STRONG model',strong_model_providers:'STRONG providers',strong_model_allow_provider_fallback:'STRONG provider fallback',vision_model:'Vision model',vision_fallback_models:'Vision fallback',batch_stt_model:'Batch STT model',tts_provider:'TTS provider',tts_fallback_provider:'TTS fallback',tts_voice:'TTS voice',default_voice_reply_mode:'Default voice reply mode',realtime_model:'Realtime Beta model',model_catalog:'Allowed model catalog'};
const runtimeConfigLists=new Set(['fast_model_providers','strong_model_providers','vision_fallback_models','model_catalog']);
const runtimeConfigBooleans=new Set(['fast_model_allow_provider_fallback','strong_model_allow_provider_fallback']);
function runtimeValue(value){return Array.isArray(value)?value.join(', '):value===true?'true':value===false?'false':String(value??'')}
function runtimeShortValue(value){
 const raw=runtimeValue(value);if(!raw)return 'Не задано';
 const model=raw.includes('/')?raw.split('/').pop():raw;
 return model.replace(/[_-]+/g,' ').replace(/\b(qwen|deepseek|gemini|voxtral)\b/gi,word=>word[0].toUpperCase()+word.slice(1)).replace(/\s\d{2}\s\d{2}$/,'').slice(0,42)
}
function runtimeConfigRow(field,entry){return `<div class="row runtime-config"><div class="body"><strong>${esc(runtimeConfigLabels[field]||field)}</strong><small>${esc(runtimeValue(entry.value))} · ${esc(entry.source)}</small></div><div><button class="secondary" type="button" data-admin-config="${esc(field)}">Изменить</button>${entry.source==='ADMIN'?`<button class="secondary" type="button" data-admin-reset="${esc(field)}">Сбросить к ENV</button>`:''}</div></div>`}
function runtimeSection(title,fields,summary,open=false){return `<details class="runtime-section" ${open?'open':''}><summary><span>${esc(title)}</span><small>${esc(summary)}</small>${icon('chevron')}</summary><div class="runtime-section-body">${fields}</div></details>`}
function adminRuntimeSettings(s){
 const config=s.admin_runtime_config;if(!config?.fields)return '';
 const fields=config.fields,effective=s.effective_ai||{};
 const model=effective.effective_model||fields.fast_model,vision=effective.vision||fields.vision_model,tts=effective.tts||{provider:fields.tts_provider?.value,provider_source:fields.tts_provider?.source,voice:fields.tts_voice?.value,voice_source:fields.tts_voice?.source};
 const current=`<h4>Сейчас для меня</h4><div class="effective-config"><div><small>Effective model</small><strong>${esc(model?.value||'—')}</strong><span>${esc(model?.source||'DEFAULT')}</span></div><div><small>Vision</small><strong>${esc(vision?.value||'—')}</strong><span>${esc(vision?.source||'DEFAULT')}</span></div><div><small>TTS</small><strong>${esc(tts.provider||'—')} / ${esc(tts.voice||'—')}</strong><span>${esc(tts.provider_source||tts.voice_source||'DEFAULT')}</span></div></div><small>FAST default и STRONG fallback — настройки router, а не пользовательский override.</small>`;
 const rows=names=>names.map(name=>runtimeConfigRow(name,fields[name])).join('');
 const groups=[
  runtimeSection('Текущая конфигурация',current,`${runtimeShortValue(model?.value)} · ${model?.source||'DEFAULT'}`,true),
  runtimeSection('Основная модель',rows(['fast_model','fast_model_providers','fast_model_allow_provider_fallback','strong_model','strong_model_providers','strong_model_allow_provider_fallback']),`${runtimeShortValue(fields.fast_model.value)} · ${fields.fast_model.source}`),
  runtimeSection('Vision',rows(['vision_model','vision_fallback_models']),`${runtimeShortValue(fields.vision_model.value)} · ${fields.vision_model.source}`),
  runtimeSection('Голос',rows(['batch_stt_model','tts_provider','tts_fallback_provider','tts_voice','default_voice_reply_mode']),`${runtimeShortValue(fields.tts_voice.value)} · ${fields.tts_voice.source}`),
  runtimeSection('Realtime Beta',rows(['realtime_model']),`${runtimeShortValue(fields.realtime_model.value)} · ${fields.realtime_model.source}`),
  runtimeSection('Каталог моделей',rows(['model_catalog']),`${Array.isArray(fields.model_catalog.value)?fields.model_catalog.value.length:0} моделей`),
 ].join('');
 const audit=config.updated_at?`Последнее изменение: ${esc(new Date(config.updated_at).toLocaleString('ru-RU'))}${config.updated_by!=null?` · admin ${esc(config.updated_by)}`:''}`:'Изменений администратора ещё не было.';
 return `<section class="card admin-ai"><div class="card-head"><h3>AI & Voice · admin</h3></div><div class="runtime-config-list">${groups}</div><small>${audit}</small><small>Секреты и ключи здесь не отображаются. Значения применяются к новым запросам сразу.</small></section>`
}
function settings(){const s=data.settings,b=s.briefing;return `<h1>Настройки</h1><p class="subtle">Фокус, ясность и контроль.</p>${card('Аккаунт',`<div class="setting"><label>Часовой пояс</label><button data-form="timezone">${esc(s.timezone)} ›</button></div><div class="setting"><label>Режим ответов в Telegram</label><select id="mode">${[['text','Текст'],['voice','Голос'],['voice_and_text','Голос + текст']].map(([k,v])=>`<option value="${k}" ${s.mode===k?'selected':''}>${v}</option>`).join('')}</select></div>`)}${card('Утренний брифинг',`<div class="setting"><label for="brief-enabled">Присылать каждый день</label><input id="brief-enabled" type="checkbox" ${b.enabled?'checked':''}></div><div class="setting"><label for="brief-time">По местному времени</label><input id="brief-time" type="time" value="${esc(b.time)}"></div><div class="setting"><label>Темы и город</label><button data-form="briefing">Настроить ›</button></div><small>${esc(b.topics)}</small>`)}${adminRuntimeSettings(s)}${betaSettings(s)}${card('Правила',`${data.rules.map(r=>`<div class="row"><div class="body">${esc(r.description)}</div><button data-delete="delete_behavior_rule" data-id="${r.id}" aria-label="Удалить правило">×</button></div>`).join('')}<button class="secondary" data-form="rule">＋ Новое правило</button>`)}${card('Память',`<p class="subtle">Можно очистить историю диалога. Заметки, люди и планы сохранятся.</p><button class="secondary" id="clear-chat">Очистить диалог</button>`)}<p class="subtle">Подключение iPhone и управление AI доступны в настройках бота.</p>`}
function chat(){const visible=data.history.filter(m=>data.settings?.mode!=='voice'||m.role!=='assistant');return `<h1>Я рядом</h1><p class="subtle">Спроси, расскажи или сохрани мысль.</p><div class="chat">${visible.map(m=>`<div class="bubble ${m.role==='user'?'user':'assistant'}">${esc(m.content)}</div>`).join('')||empty('«Напомни завтра позвонить маме»<br>«Запиши 350 рублей на кофе»')}<div id="thinking" class="subtle" hidden>Собираю ответ…</div></div><form id="chat-form" class="composer"><span id="composer-status" class="composer-status" role="status" ${statusMessage?'':'hidden'}>${esc(statusMessage)}</span><input id="chat-input" autocomplete="off" enterkeyhint="send" placeholder="Спроси Noema…" required maxlength="12000"><button class="chat-voice-orb" aria-label="Голосовой запрос" type="button" data-voice><canvas class="membrane" width="128" height="128" aria-hidden="true"></canvas></button></form>`}
function render(){content.innerHTML=({home,archive,people,tasks,reminders,budget,settings,chat}[page]||home)();const orb=content.querySelector('.ambient-orb');if(orb)orb.outerHTML='<canvas class="membrane" width="500" height="500" aria-hidden="true"></canvas>';if(page==='chat')say(statusMessage);document.querySelectorAll('nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(tg){page==='home'?tg.BackButton.hide():tg.BackButton.show()}}
function go(next){page=next;search='';filter='all';render();window.scrollTo({top:0})}
const forms={task:['Новая задача','add_task',[['text','Что сделать','textarea'],['due_date','Дата','date'],['priority','Приоритет','text']]],note:['Сохранить мысль','save_note',[['title','Заголовок','text'],['text','Заметка','textarea']]],reminder:['Напомнить','set_reminder',[['text','О чём напомнить','textarea'],['remind_at','Когда · '+data.settings.timezone,'datetime-local']]],expense:['Новый расход','add_expense',[['amount','Сумма в рублях','number'],['description','На что потрачено','text'],['category','Категория','text']]],income:['Новое поступление','add_income',[['amount','Сумма в рублях','number'],['description','Источник','text'],['category','Категория','text']]],person:['Новый человек','person_upsert',[['name','Имя','text'],['relationship','Кто это для тебя','text'],['birthday','День рождения','date'],['age','Возраст','number'],['home_city','Город','text'],['current_location','Где сейчас','text'],['projects','Проекты','text'],['notes','Что важно','textarea']]],rule:['Новое правило','save_behavior_rule',[['description','Как мне отвечать и помогать','textarea']]],timezone:['Часовой пояс','set_timezone',[['timezone_name','Например Europe/Moscow','text']]],briefing:['Твой брифинг','set_briefing_preferences',[['topics','Интересные темы','text'],['city','Город для погоды','text']]]};
let editAction='';
class SentenceChunker{
 constructor(){this.buffer=''}
 feed(text){
  this.buffer+=text;const out=[];let match;
  while((match=this.buffer.match(/^.*?[.!?…](?:\s+|$)/s))){out.push(match[0].trim());this.buffer=this.buffer.slice(match[0].length)}
  if(!out.length&&this.buffer.length>=180){const cut=Math.max(this.buffer.lastIndexOf(', ',180),this.buffer.lastIndexOf('; ',180),this.buffer.lastIndexOf(': ',180),this.buffer.lastIndexOf(' ',180));if(cut>=56){out.push(this.buffer.slice(0,cut+1).trim());this.buffer=this.buffer.slice(cut+1)}}
  return out.filter(value=>value.length>1)
 }
 flush(){const value=this.buffer.trim();this.buffer='';return value?[value]:[]}
}
function sanitizeSpeechText(value){
 let text=String(value||'').replace(/```[\s\S]*?```/g,' ').replace(/`[^`]*`/g,' ');
 text=text.split(/\r?\n/).filter(line=>!/^\s*(?:tool(?:_call)?|debug|metadata|function|arguments?|trace|json)\s*[:=]/i.test(line)&&!/^\s*\|?(?:\s*:?-{3,}:?\s*\|)+\s*$/.test(line)).map(line=>line.replace(/^\s{0,3}#{1,6}\s*/,'').replace(/^\s*(?:[-*+]\s+|\d+[.)]\s+)/,'')).join(' ');
 return text.replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/https?:\/\/\S+/gi,'ссылка').replace(/[\*_~`|\[\]{}<>]+/g,' ').replace(/\s+([,.!?;:])/g,'$1').replace(/\s{2,}/g,' ').trim()
}
const TTS_ENGINE={edge:1,browser:2};
function browserVoice(){const all=(window.speechSynthesis?.getVoices?.()||[]).sort((a,b)=>a.name.localeCompare(b.name));const russian=all.filter(voice=>/^ru/i.test(voice.lang));return russian.find(voice=>/dmitry|yuri|русск/i.test(voice.name))||russian[0]||all[0]||null}
function voiceCode(voice){const name=String(voice?.name||'default');return [...name].reduce((sum,char)=>(sum*31+char.charCodeAt(0))%900000,7)}
function publishVoiceTelemetry(metrics){
 const safe={};for(const [name,value] of Object.entries(metrics)){if(Number.isFinite(value)&&value>=0&&value<=900000){safe[name]=Math.round(value*10)/10;telemetry.record(name,value)}}
 if(window.NoemaTelemetryEnabled&&Object.keys(safe).length)fetch('/api/v1/miniapp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({init_data:tg?.initData||'',action:'telemetry_record',args:{metrics:safe}})}).catch(()=>{})
}
class SpeechQueue{
 constructor(onMetric){this.items=[];this.playing=false;this.audio=null;this.idle=[];this.onMetric=onMetric;this.route=null;this.voice=null;this.allowBrowserFallback=true;this.responseStarted=0;this.firstStarted=false}
 beginResponse(started){this.cancel();const runtime=data.settings?.voice_runtime||{},provider=runtime.tts_provider||'edge',fallback=runtime.tts_fallback_provider||'browser';this.route=provider==='browser'?'browser':provider==='edge'?'edge':null;this.allowBrowserFallback=fallback==='browser';this.voice=this.route==='browser'?browserVoice():null;this.responseStarted=started;this.firstStarted=false;if(this.route==='browser'){this.metric('tts_engine_name',TTS_ENGINE.browser);this.metric('tts_voice_name',voiceCode(this.voice))}if(this.route==='edge'){this.metric('tts_engine_name',TTS_ENGINE.edge);this.metric('tts_voice_name',voiceCode({name:runtime.tts_voice||'edge'}))}}
 metric(name,value){this.onMetric?.(name,value)}
 enqueue(raw){const text=sanitizeSpeechText(raw);if(text){this.items.push({text,queuedAt:performance.now()});this.metric('speech_text_length_chars',text.length);this.pump()}}
 cancel(){this.items=[];this.audio?.pause();this.audio=null;window.speechSynthesis?.cancel();this.playing=false;this.finish()}
 whenIdle(){return this.playing||this.items.length?new Promise(resolve=>this.idle.push(resolve)):Promise.resolve()}
 finish(){if(this.playing||this.items.length)return;this.idle.splice(0).forEach(resolve=>resolve())}
 markStarted(){if(this.firstStarted)return;this.firstStarted=true;this.metric('tts_first_start_ms',performance.now()-this.responseStarted)}
 async pump(){if(this.playing||!this.items.length)return this.finish();this.playing=true;const item=this.items.shift();try{await this.play(item)}finally{this.playing=false;this.pump()}}
 async play(item){
  this.metric('tts_queue_wait_ms',performance.now()-item.queuedAt);
  if(this.route==='browser')return this.playBrowser(item.text);
  if(this.route==='edge')return this.playEdge(item.text);
  try{await this.playEdge(item.text,true)}catch(error){if(!this.allowBrowserFallback)throw error;this.route='browser';this.voice=browserVoice();this.metric('tts_prepare_ms',0);this.metric('tts_engine_name',TTS_ENGINE.browser);this.metric('tts_voice_name',voiceCode(this.voice));await this.playBrowser(item.text)}
 }
 async speechResponse(text){const prepared=performance.now();const response=await fetch('/api/v1/miniapp/speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({init_data:tg?.initData||'',text})});if(!response.ok)throw Error('EDGE_TTS_UNAVAILABLE');const blob=await response.blob();this.metric('tts_prepare_ms',performance.now()-prepared);return {blob,voice:response.headers.get('X-Noema-TTS-Voice')||'edge'} }
 async playEdge(text,selectRoute=false){const result=await this.speechResponse(text);if(selectRoute){this.route='edge';this.metric('tts_engine_name',TTS_ENGINE.edge);this.metric('tts_voice_name',voiceCode({name:result.voice}))}const url=URL.createObjectURL(result.blob);await new Promise((resolve,reject)=>{const audio=this.audio=new Audio(url);audio.onplaying=()=>this.markStarted();audio.onended=()=>{URL.revokeObjectURL(url);resolve()};audio.onerror=()=>{URL.revokeObjectURL(url);reject(Error('EDGE_TTS_UNAVAILABLE'))};audio.play().catch(reject)});this.audio=null}
 async playBrowser(text){await new Promise(resolve=>{if(!('speechSynthesis'in window))return resolve();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='ru-RU';utterance.voice=this.voice;utterance.rate=.98;utterance.onstart=()=>this.markStarted();utterance.onend=utterance.onerror=resolve;window.speechSynthesis.speak(utterance)})}
}
class VoiceController{
 constructor(){this.state='idle';this.speech=new SpeechQueue((name,value)=>this.metric(name,value));this.jobId='';this.responseMetrics=null}
 sync(){for(const button of document.querySelectorAll('[data-voice]'))button.setAttribute('aria-label',this.state==='recording'?'Закончить запись':this.state==='processing'?'Готовлю ответ':this.state==='speaking'?'Остановить и записать новый запрос':'Голосовой запрос')}
 setState(state){this.state=state;this.sync();NoemaMembrane?.setState({recording:'listening',processing:'thinking',speaking:'responding',idle:'idle'}[state]||'idle')}
 metric(name,value){if(this.responseMetrics&&!Number.isFinite(this.responseMetrics[name]))this.responseMetrics[name]=value}
 finishMetrics(){if(!this.responseMetrics)return;this.responseMetrics.total_ms=performance.now()-this.responseMetrics.startedAt;delete this.responseMetrics.startedAt;publishVoiceTelemetry(this.responseMetrics);this.responseMetrics=null}
 async toggle(){if(preview){say('Голос доступен при открытии через Telegram.');return}if(this.state==='recording')return this.stopRecording();if(this.state==='speaking'){this.speech.cancel();this.setState('idle')}if(this.state==='processing'){say('Запрос уже выполняется. Можно перейти на другой экран.');return}return this.startRecording()}
 async startRecording(){try{this.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1},video:false});const mime=['audio/webm;codecs=opus','audio/mp4'].find(value=>MediaRecorder.isTypeSupported(value));this.recorder=new MediaRecorder(this.stream,mime?{mimeType:mime}:{});this.chunks=[];this.recorder.ondataavailable=event=>{if(event.data.size)this.chunks.push(event.data)};this.recorder.onstop=()=>this.processRecording();this.recorder.start();this.setState('recording');say('Слушаю. Нажми на сферу ещё раз, когда закончишь.')}catch{this.setState('idle');say('Не удалось включить микрофон. Проверь разрешение Telegram или браузера.')}}
 stopRecording(){if(this.recorder?.state==='recording')this.recorder.stop()}
 async processRecording(){const chunks=this.chunks||[],mime=this.recorder?.mimeType||'audio/webm';this.stream?.getTracks().forEach(track=>track.stop());this.stream=null;this.recorder=null;if(!chunks.length){this.setState('idle');return}this.setState('processing');say('Распознаю речь…');const progress=setTimeout(()=>{if(this.state==='processing')say('Распознавание ещё выполняется…')},8000);try{const form=new FormData();form.append('init_data',tg?.initData||'');form.append('audio',new Blob(chunks,{type:mime}),'voice.'+(mime.includes('mp4')?'mp4':'webm'));const response=await fetch('/api/v1/miniapp/voice/transcribe',{method:'POST',body:form});const result=await response.json();if(!response.ok||!result.ok)throw Error(result.error||'Речь не распознана.');await this.ask(result.data?.text||'')}catch(error){this.setState('idle');say(error.message||'Не удалось обработать голос.')}finally{clearTimeout(progress)}}
 async ask(text){const mode=data.settings?.mode||'text',speak=mode==='voice'||mode==='voice_and_text',chunker=new SentenceChunker(),startedAt=performance.now();this.responseMetrics={startedAt};if(speak)this.speech.beginResponse(startedAt);this.setState('processing');say('Собираю ответ…');const progress=setTimeout(()=>{if(this.state==='processing')say('Ответ ещё готовится…')},8000);try{const answer=await streamChat(text,{render:mode!=='voice',onJob:id=>this.jobId=id,onProgress:message=>say(message),onDelta:delta=>{this.metric('total_response_start_ms',performance.now()-startedAt);if(speak)for(const sentence of chunker.feed(delta)){this.metric('tts_first_chunk_ms',performance.now()-startedAt);this.setState('speaking');this.speech.enqueue(sentence)}}});if(speak)for(const sentence of chunker.flush()){this.metric('tts_first_chunk_ms',performance.now()-startedAt);this.setState('speaking');this.speech.enqueue(sentence)}await load();if(speak)await this.speech.whenIdle();this.setState('idle');say('');return answer}finally{clearTimeout(progress);this.finishMetrics()}}
}
const voiceController=window.NoemaVoiceController=window.NoemaVoiceController||new VoiceController();
async function recordVoice(){return voiceController.toggle()}
function openAdminRuntimeConfig(field){const entry=data.settings?.admin_runtime_config?.fields?.[field];if(!entry)return;editAction='admin_runtime_config_set';document.querySelector('#form-title').textContent=runtimeConfigLabels[field]||field;const value=runtimeValue(entry.value);let control;if(runtimeConfigBooleans.has(field)){control=`<select name="value"><option value="true" ${value==='true'?'selected':''}>true</option><option value="false" ${value==='false'?'selected':''}>false</option></select>`}else if(field==='tts_provider'||field==='tts_fallback_provider'){const options=field==='tts_provider'?['edge','browser']:['edge','browser','none'];control=`<select name="value">${options.map(option=>`<option value="${option}" ${value===option?'selected':''}>${option}</option>`).join('')}</select>`}else if(field==='default_voice_reply_mode'){control=`<select name="value">${['auto','text','voice','voice_and_text'].map(option=>`<option value="${option}" ${value===option?'selected':''}>${option}</option>`).join('')}</select>`}else if(runtimeConfigLists.has(field)){control=`<textarea name="value" required>${esc(value)}</textarea>`}else{control=`<input name="value" value="${esc(value)}" required>`}document.querySelector('#fields').innerHTML=`<input type="hidden" name="field" value="${esc(field)}"><label>Текущее значение · ${esc(entry.source)}${control}</label><small>Проверяется до сохранения. Секреты здесь недоступны.</small>`;document.querySelector('#editor').showModal()}
function openForm(name,values={},actionOverride='',titleOverride=''){const [title,action,fields]=forms[name];editAction=actionOverride||action;document.querySelector('#form-title').textContent=titleOverride||title;const fieldKeys=new Set(fields.map(x=>x[0]));const hidden=Object.entries(values).filter(([key])=>key.endsWith('_id')&&!fieldKeys.has(key)).map(([key,value])=>`<input type="hidden" name="${key}" value="${esc(value)}">`).join('');document.querySelector('#fields').innerHTML=fields.map(([key,label,type])=>{const value=values[key]??(name==='timezone'?data.settings.timezone:name==='briefing'?data.settings.briefing[key]||'':key==='priority'?'normal':'');const optional=['relationship','notes','due_date','city','title','birthday','projects','category','priority','age','home_city','current_location'].includes(key),numberAttrs=type==='number'?(key==='age'?'min="0" step="1"':'min="0.01" step="0.01"'):'';return `<label>${esc(label)}${type==='textarea'?`<textarea name="${key}" ${optional?'':'required'}>${esc(value)}</textarea>`:`<input name="${key}" type="${type}" ${numberAttrs} value="${esc(value)}" ${optional?'':'required'}>`}</label>`}).join('')+hidden;document.querySelector('#editor').showModal()}
function localDateTime(value){if(!value)return '';const d=new Date(value);const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function openEdit(type,id){let item,values,action,title,form;if(type==='task'){item=data.tasks.find(x=>x.id===id);values={text:item?.text,due_date:item?.due_date,priority:item?.priority,task_id:id};action='update_task';title='Изменить задачу';form='task'}if(type==='note'){item=data.notes.find(x=>x.id===id);values={title:item?.title,text:item?.text,note_id:id};action='update_note';title='Изменить заметку';form='note'}if(type==='reminder'){item=data.reminders.find(x=>x.id===id);values={text:item?.text,remind_at:localDateTime(item?.remind_at_utc),reminder_id:id};action='update_reminder';title='Изменить напоминание';form='reminder'}if(type==='expense'){item=(budgetData?.items||data.expenses).find(x=>x.id===id);values={amount:item?.amount,description:item?.description,category:item?.category,expense_id:id};action='update_expense';title='Изменить операцию';form=item?.kind==='income'?'income':'expense'}if(type==='person'){item=data.people.find(x=>x.id===id);values={name:item?.name,relationship:item?.relationship,birthday:item?.birthday,age:item?.age,home_city:item?.home_city,current_location:item?.current_location,projects:item?.projects,notes:item?.notes,person_id:id};action='update_person';title='Изменить человека';form='person'}if(type==='rule'){item=data.rules.find(x=>x.id===id);values={description:item?.description,rule_id:id};action='update_behavior_rule';title='Изменить правило';form='rule'}if(item)openForm(form,values,action,title)}
async function mutate(action,args){if(busy)return;busy=true;try{await api(action,args);await load();if(page==='budget')await loadBudget();say('')}catch(e){say(e.message)}finally{busy=false}}
document.addEventListener('click',async e=>{const b=e.target.closest('button,[role=button]');if(!b)return;
  if(b.dataset.page&&!(homeEditing&&b.closest('.home-grid')))go(b.dataset.page);
  if(b.id==='record')await recordVoice(b);
  if(b.dataset.filter){filter=b.dataset.filter;render()}
  if(b.dataset.form)openForm(b.dataset.form);
  if(b.dataset.adminConfig)openAdminRuntimeConfig(b.dataset.adminConfig);
  if(b.dataset.adminReset)await mutate('admin_runtime_config_reset',{field:b.dataset.adminReset});
  if(b.dataset.edit)openEdit(b.dataset.edit,Number(b.dataset.id));
  if(b.dataset.toggle)await mutate('task_toggle',{id:Number(b.dataset.toggle)});
  if(b.dataset.reminder)await mutate('reminder_done',{id:Number(b.dataset.reminder)});
  if(b.dataset.delete&&confirm('Удалить эту запись?')){const keys={delete_note:'note_id',delete_task:'task_id',delete_person:'person_id',delete_expense:'expense_id',delete_reminder:'reminder_id',delete_behavior_rule:'rule_id'};await mutate(b.dataset.delete,{[keys[b.dataset.delete]]:Number(b.dataset.id)})}
  if(b.id==='cancel')document.querySelector('#editor').close();
  if(b.id==='clear-chat'&&confirm('Очистить историю диалога?'))await mutate('clear_history',{});
});
document.addEventListener('change',async e=>{if(e.target.id==='mode')await mutate('mode',{mode:e.target.value});if(e.target.id==='brief-enabled')await mutate('set_briefing_preferences',{enabled:e.target.checked});if(e.target.id==='brief-time')await mutate('set_briefing_preferences',{time:e.target.value});if(e.target.id==='realtime-beta'){await mutate('set_experimental_realtime',{enabled:e.target.checked});window.NoemaRealtimeBeta?.setEnabled(e.target.checked,{wakeEnabled:Boolean(data.settings?.experimental_wake_enabled)}).catch(()=>say('Не удалось загрузить Beta-режим.'))}if(e.target.id==='wake-word-beta'){await mutate('set_experimental_wake',{enabled:e.target.checked});window.NoemaRealtimeBeta?.setWakeEnabled?.(e.target.checked)}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;search=e.target.value;render();const input=document.querySelector('#search');input.focus();input.setSelectionRange(pos,pos)}});
document.querySelector('#edit-form').addEventListener('submit',async e=>{e.preventDefault();const args=Object.fromEntries(new FormData(e.target));if(args.amount)args.amount=Number(args.amount);await mutate(editAction,args);if(!notice.textContent)document.querySelector('#editor').close()});
async function streamChat(text,options={}){const response=await fetch('/api/v1/miniapp/chat-stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({init_data:tg?.initData||'',text}),signal:options.signal});if(!response.ok)throw Error(await response.text()||'Не удалось получить ответ.');const thread=options.render===false?null:document.querySelector('.chat'),thinking=document.querySelector('#thinking');let bubble=null;if(thread){bubble=document.createElement('div');bubble.className='bubble assistant streaming';(thinking||thread).before?.(bubble)}const reader=response.body.getReader(),decoder=new TextDecoder();let pending='',answer='';while(true){const {value,done}=await reader.read();pending+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=pending.split('\n');pending=lines.pop()||'';for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==='job')options.onJob?.(event.job_id);if(event.type==='progress'){if(thinking){thinking.textContent=event.text;thinking.hidden=false}options.onProgress?.(event.text)}if(event.type==='delta'){answer+=event.text;const follow=thread?.isConnected&&(thread.scrollHeight-thread.scrollTop-thread.clientHeight<72);if(bubble?.isConnected)bubble.textContent+=event.text;if(follow)thread.scrollTop=thread.scrollHeight;options.onDelta?.(event.text)}if(event.type==='cancelled')throw new DOMException('Generation stopped','AbortError');if(event.type==='error')throw Error('Не удалось получить ответ. Попробуй ещё раз.')}if(done)break}return answer}
let chatSubmitting=false;
document.addEventListener('submit',async e=>{if(e.target.id!=='chat-form')return;e.preventDefault();if(chatSubmitting)return;const input=document.querySelector('#chat-input'),text=input.value.trim();if(!text)return;chatSubmitting=true;input.value='';document.querySelector('#thinking').hidden=false;try{await voiceController.ask(text)}catch(err){say(err.message);input.value=text}finally{chatSubmitting=false;const thinking=document.querySelector('#thinking');if(thinking)thinking.hidden=true}});
// Bootstrapping and screen composition live in screens.js.
